dear_guest = ['Newton', 'Arnold', 'Enshtein']
#print(f"Dear friend {dear_guest[0]}, come back tomorrow!")
#print(f"Dear friend {dear_guest[1]}, come back tomorrow!")
#print(f"Dear friend {dear_guest[2]}, come back tomorrow!")
#print(dear_guest[2])
del dear_guest[2]
print(dear_guest)
dear_guest.insert(2,'Leonov')
print(dear_guest)
print(f"Dear friend {dear_guest[0]}, come back tomorrow!")
print(f"Dear friend {dear_guest[1]}, come back tomorrow!")
print(f"Dear friend {dear_guest[2]}, come back tomorrow!")
print('We are decided invite 3 new guest')
dear_guest.insert(0, 'Mihail')
dear_guest.insert(2, 'Olya')
dear_guest.append('Leonid')
print(dear_guest)
print(f"Dear friend {dear_guest[0]}, come back tomorrow !")
print(f"Dear friend {dear_guest[1]}, come back tomorrow!")
print(f"Dear friend {dear_guest[2]}, come back tomorrow!")
print(f"Dear friend {dear_guest[3]}, come back tomorrow!")
print(f"Dear friend {dear_guest[4]}, come back tomorrow!")
print(f"Dear friend {dear_guest[5]}, come back tomorrow!")
print('We are need invite only 2 guest')

guest_L = dear_guest.pop()
print(f"Dear {guest_L}, I need canceled my invite on happy birthday. I am very sorry!")
guest_A = dear_guest.pop(3)
print(f"Dear {guest_A}, I need canceled my invite on happy birthday. I am very sorry!")
guest_O = dear_guest.pop(2)
print(f"Dear {guest_O}, I need canceled my invite on happy birthday. I am very sorry!")
guest_N = dear_guest.pop(1)
print(f"Dear {guest_N}, I need canceled my invite on happy birthday. I am very sorry!")
print(f"Dear friend {dear_guest[0]}, your invitation remains valid..")
del dear_guest[0]
del dear_guest[0]
print(dear_guest)